"""empty message

Revision ID: 06836065d1cd
Revises: 
Create Date: 2023-10-28 19:51:14.471182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06836065d1cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.String(length=50), nullable=True))
        batch_op.alter_column('grade',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('FIRST', 'SECOND', 'THIRD', 'FOURTH', 'FIFTH', 'SIXTH', 'SEVENTH', 'EIGHTH', 'NINTH', 'TENTH', 'ELEVENTH', 'TWELFTH', 'FRESHMAN', 'SOPHOMORE', 'JUNIOR', 'SENIOR', name='gradeenum'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('grade',
               existing_type=sa.Enum('FIRST', 'SECOND', 'THIRD', 'FOURTH', 'FIFTH', 'SIXTH', 'SEVENTH', 'EIGHTH', 'NINTH', 'TENTH', 'ELEVENTH', 'TWELFTH', 'FRESHMAN', 'SOPHOMORE', 'JUNIOR', 'SENIOR', name='gradeenum'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
        batch_op.drop_column('first_name')
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###
