"""empty message

Revision ID: 0919b4726e38
Revises: 06836065d1cd
Create Date: 2023-10-28 19:56:32.449622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0919b4726e38'
down_revision = '06836065d1cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('grade')
        batch_op.drop_column('favorite_subject')
        batch_op.drop_column('registration_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('favorite_subject', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('grade', sa.VARCHAR(length=9), nullable=False))

    # ### end Alembic commands ###
