name: Complete Gamified Learning Platform Testing Suite
on:
    workflow_dispatch
jobs:
    update:
        name: Run GLP Tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            
            - name: Python Setup
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'  
                cache: pip
      
            - name: Install Requirements
              run: pip install -r requirements.txt
      
            - name: Run All Tests
              run: python -m coverage run -m pytest 

            - name: Print Coverage
              run: python -m coverage report 